import QtQuick
import QtQuick3D
import QtQuick3D.AssetUtils

import QGroundControl

Node {
    id: externalMap

    property var    viewer3DSettings:      QGroundControl.corePlugin.viewer3DSettings
    property string modelFilePath:          viewer3DSettings.external3DMapFilePath.rawValue
    property real   unitToMeters:           Math.max(0.000001, Number(viewer3DSettings.external3DMapUnitToMeters.rawValue))
    property real   userScale:              Math.max(0.000001, Number(viewer3DSettings.external3DMapScale.rawValue))
    property real   yawDegrees:             Number(viewer3DSettings.external3DMapYaw.rawValue)
    property real   sceneUnitsPerMeter:     10.0
    property real   sceneScale:             unitToMeters * userScale * sceneUnitsPerMeter

    readonly property string sourceUrl:      _toFileUrl(modelFilePath)
    readonly property string fileExtension:  _fileExtension(modelFilePath)
    readonly property bool   hasModelFile:   sourceUrl.length > 0
    readonly property bool   runtimeLoadable: ["obj", "gltf", "glb"].indexOf(fileExtension) !== -1
    readonly property bool   qmlLoadable:     fileExtension === "qml"
    readonly property bool   balsamSource:    ["fbx", "dae", "stl", "ply"].indexOf(fileExtension) !== -1

    // 该文本由 Viewer3DModel.qml 叠加显示，用于提示模型导入状态或必要的转换步骤。

    readonly property string statusText:      _statusText()
    readonly property bool   hasBlockingIssue: statusText.length > 0

    function _isPlaceholder(path) {
        var text = String(path || "").trim()
        return text.length === 0 || text === "Please select an external 3D model file"
    }

    function _fileExtension(path) {
        if (_isPlaceholder(path)) {
            return ""
        }
        var clean = String(path).replace(/\\/g, "/")
        clean = clean.split("?")[0].split("#")[0]
        var dot = clean.lastIndexOf(".")
        return dot >= 0 ? clean.substring(dot + 1).toLowerCase() : ""
    }

    function _toFileUrl(path) {
        if (_isPlaceholder(path)) {
            return ""
        }

        var clean = String(path).trim().replace(/\\/g, "/")
        if (clean.indexOf("file://") === 0 || clean.indexOf("qrc:/") === 0 || clean.indexOf(":/") === 0) {
            return clean
        }

        // Windows: F:/map/model.obj -> file:///F:/map/model.obj
        if (/^[A-Za-z]:\//.test(clean)) {
            return "file:///" + clean
        }

        // Linux/macOS: /home/user/model.obj -> file:///home/user/model.obj
        if (clean[0] === "/") {
            return "file://" + clean
        }

        return "file:///" + clean
    }

    function _statusText() {
        if (!hasModelFile) {
            return qsTr("Select an external 3D model file before enabling the external model map source.")
        }

        if (balsamSource) {
            return qsTr("This authoring format must be imported from Application Settings > Fly View > 3D View so Qt Balsam can convert it to Quick3D QML first.")
        }

        if (!runtimeLoadable && !qmlLoadable) {
            return qsTr("Unsupported external 3D model format. Use OBJ, glTF/GLB, or a QML file generated by Qt Balsam.")
        }

        if (runtimeLoadable && runtimeModel.status === RuntimeLoader.Error) {
            return qsTr("Failed to load external 3D model: %1").arg(runtimeModel.errorString)
        }

        if (qmlLoadable && qmlModelLoader.status === Loader.Error) {
            return qsTr("Failed to load external 3D map QML file.")
        }

        var lat = Number(viewer3DSettings.external3DMapOriginLatitude.rawValue)
        var lon = Number(viewer3DSettings.external3DMapOriginLongitude.rawValue)
        if (lat === 0 && lon === 0) {
            return qsTr("External 3D map origin is 0,0. Set the real WGS84 origin if this model is not located at the equator/prime meridian.")
        }

        return ""
    }

    Node {
        id: georeferencedModelRoot

        // Viewer3D 车辆和航线使用“米 * 10”的 Quick3D 场景尺度。这里先做模型单位到米的换算，再乘用户比例。

        scale: Qt.vector3d(externalMap.sceneScale, externalMap.sceneScale, externalMap.sceneScale)

        // 模型局部原点对应设置中的 originLat/originLon； yaw 用于把模型北向旋到 QGC ENU 坐标系。

        eulerRotation.z: externalMap.yawDegrees

        RuntimeLoader {
            id: runtimeModel
            visible: externalMap.runtimeLoadable
            source: externalMap.runtimeLoadable ? externalMap.sourceUrl : ""
        }

        Loader3D {
            id: qmlModelLoader
            active: externalMap.qmlLoadable
            source: externalMap.qmlLoadable ? externalMap.sourceUrl : ""
        }
    }
}
